// data.mjs — the project rows, one place, used for both the PDF and the CSV.
//
// Every field is taken from Communications-Based Train Control (Vol. 1, Ch. 10
// and 11) or from a cbtcbook.com case-study article. A field that could not be
// verified against one of those is left empty and renders as an em dash — it is
// NOT filled with a plausible value. A reference table that people cite is
// worth more with honest gaps than with confident guesses.

export const FIELDS = [
  ["system", "System / line"],
  ["country", "Country"],
  ["supplier", "CBTC supplier"],
  ["platform", "Platform"],
  ["goa", "GoA"],
  ["opened", "Opened / converted"],
  ["length", "Length"],
  ["stations", "Stations"],
  ["headway", "Peak headway / throughput"],
  ["note", "Note"],
];

export const PROJECTS = [
  // ── United States ────────────────────────────────────────────────────────
  {
    system: "NYCT L Line (Canarsie)",
    country: "US",
    supplier: "Siemens",
    platform: "Trainguard MT",
    goa: "2",
    opened: "2006 partial · 2009 full",
    length: "~15 km",
    stations: "",
    headway: "24–29 tph",
    note: "The US flagship retrofit. Design 1999–2001, install 2001–2006, three segment cutovers, ~8 months shadow running. Roughly $48M per km. No civil works; throughput up from ~20 tph.",
  },
  {
    system: "NYCT 7 Line (Flushing)",
    country: "US",
    supplier: "Siemens",
    platform: "Trainguard MT",
    goa: "2",
    opened: "",
    length: "40 km",
    stations: "",
    headway: "",
    note: "Validated through thousands of scenarios on a full-system simulator running production software before any test train moved in Manhattan.",
  },
  {
    system: "BART — TCMP",
    country: "US",
    supplier: "Hitachi Rail",
    platform: "SelTrac",
    goa: "2",
    opened: "Awarded 2018",
    length: "131 route-km",
    stations: "",
    headway: "30 tph target",
    note: "The most substantial current US CBTC implementation. Fleet- and function-phased.",
  },
  {
    system: "Honolulu Skyline",
    country: "US",
    supplier: "Hitachi Rail",
    platform: "Hitachi CBTC",
    goa: "4",
    opened: "2023 (service 2023–2026)",
    length: "15.5 mi",
    stations: "14",
    headway: "",
    note: "Single-prime contract, ~$398M, 78 railcars, vehicles co-designed for the CBTC. First US mass-transit line certified for unattended operation.",
  },
  {
    system: "JFK AirTrain",
    country: "US",
    supplier: "Bombardier (now Alstom)",
    platform: "CITYFLO / Innovia",
    goa: "4",
    opened: "2003",
    length: "8.1 mi",
    stations: "",
    headway: "",
    note: "An airport system rather than a metro, and one of only two long-standing US GoA 4 operations.",
  },
  {
    system: "SFMTA Muni Metro",
    country: "US",
    supplier: "Alstom",
    platform: "CITYFLO",
    goa: "2",
    opened: "1998",
    length: "150 km",
    stations: "",
    headway: "",
    note: "An early automated train control system predating modern CBTC standards; 25+ years of tenure informs current procurement practice.",
  },
  {
    system: "PATH",
    country: "US",
    supplier: "",
    platform: "",
    goa: "1",
    opened: "",
    length: "13.8 mi",
    stations: "",
    headway: "",
    note: "Frequently overlooked in US benchmark sets.",
  },
  {
    system: "Denver International Airport A-Line",
    country: "US",
    supplier: "",
    platform: "",
    goa: "4 (part)",
    opened: "",
    length: "",
    stations: "",
    headway: "",
    note: "Some sections mixed-mode.",
  },
  {
    system: "Las Vegas Monorail",
    country: "US",
    supplier: "",
    platform: "",
    goa: "4 (part)",
    opened: "",
    length: "",
    stations: "",
    headway: "",
    note: "Partial GoA 4 operation in certain sections.",
  },
  {
    system: "MBTA Green Line",
    country: "US",
    supplier: "Alstom",
    platform: "",
    goa: "",
    opened: "In design",
    length: "",
    stations: "",
    headway: "",
    note: "Hornell, NY manufacturing is a stated competitive advantage.",
  },
  {
    system: "WMATA — Red / Green / Blue",
    country: "US",
    supplier: "Alstom · Siemens",
    platform: "",
    goa: "",
    opened: "In design",
    length: "",
    stations: "",
    headway: "",
    note: "Emphasis on open interfaces and Buy America compliance.",
  },

  // ── International benchmarks ─────────────────────────────────────────────
  {
    system: "Paris Métro Line 14",
    country: "France",
    supplier: "Siemens Mobility",
    platform: "",
    goa: "4",
    opened: "July 1998",
    length: "17.5 km (final)",
    stations: "13 (final)",
    headway: "85 s (~42 tph)",
    note: "The greenfield showcase: the first modern metro to open at GoA 4. 100% platform screen doors from day one. ~650,000 daily riders. €650–750M for the full line.",
  },
  {
    system: "Paris Métro Line 1",
    country: "France",
    supplier: "Siemens",
    platform: "Trainguard MT",
    goa: "4",
    opened: "2007–2012 conversion",
    length: "16.5 km",
    stations: "29",
    headway: "90 s (~40 tph)",
    note: "The brownfield paradigm shift: converted under traffic over a five-year phased cutover, PSDs retrofitted to 86% of platforms over five years. ~1.5M daily riders. €700M+. Throughput rose from ~20 to 27 tph.",
  },
  {
    system: "Copenhagen Metro M1 / M2",
    country: "Denmark",
    supplier: "Ansaldo STS (now Hitachi Rail)",
    platform: "",
    goa: "4",
    opened: "19 Oct 2002",
    length: "",
    stations: "",
    headway: "",
    note: "The longest uninterrupted GoA 4 record in continental Europe. 34 three-car driverless sets; unattended operation was a founding requirement, not a retrofit.",
  },
  {
    system: "Copenhagen Metro M3 Cityringen",
    country: "Denmark",
    supplier: "Ansaldo STS (now Hitachi Rail)",
    platform: "",
    goa: "4",
    opened: "29 Sep 2019",
    length: "15.5 km",
    stations: "17",
    headway: "~100 s (36 tph design)",
    note: "Turnkey contract ~€700M covering signaling, power, comms, SCADA, PSDs, control centre, depot and rolling stock. M4 Nordhavn opened 28 Mar 2020; a 4.5 km Sydhavn extension 22 Jun 2024.",
  },
  {
    system: "Vancouver SkyTrain",
    country: "Canada",
    supplier: "Bombardier / Hitachi Rail",
    platform: "SelTrac",
    goa: "4",
    opened: "1985",
    length: "",
    stations: "",
    headway: "",
    note: "Forty years of driverless operation — the deepest GoA 4 operating record behind any Western supplier's claims.",
  },
  {
    system: "Hong Kong MTR — Tsuen Wan",
    country: "Hong Kong",
    supplier: "",
    platform: "",
    goa: "",
    opened: "",
    length: "",
    stations: "",
    headway: "24 tph",
    note: "Throughput rose from 18 to 24 tph on unchanged civil infrastructure.",
  },
  {
    system: "London Underground — Jubilee",
    country: "UK",
    supplier: "Thales (now Hitachi Rail)",
    platform: "SelTrac",
    goa: "2",
    opened: "",
    length: "",
    stations: "",
    headway: "",
    note: "Delivered under the Metronet PPP model, whose contractual structure is as instructive as its engineering.",
  },
  {
    system: "Elizabeth Line (Crossrail)",
    country: "UK",
    supplier: "",
    platform: "",
    goa: "",
    opened: "",
    length: "",
    stations: "",
    headway: "",
    note: "Multi-signaling architecture at scale: CBTC in the core, conventional signaling on the outer branches, with transitions in service.",
  },
  {
    system: "Singapore MRT",
    country: "Singapore",
    supplier: "",
    platform: "",
    goa: "4",
    opened: "",
    length: "",
    stations: "",
    headway: "",
    note: "The LTA model for fully automated network expansion; fleet-phased retrofit on existing lines.",
  },
  {
    system: "Dubai Metro",
    country: "UAE",
    supplier: "",
    platform: "",
    goa: "4",
    opened: "",
    length: "",
    stations: "",
    headway: "",
    note: "Operated by Keolis-MHI. A reference case for public acceptance of unattended operation at scale.",
  },
];

export function toCsv() {
  const esc = (v) => {
    const s = String(v ?? "").trim();
    return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
  };
  const head = FIELDS.map(([, label]) => esc(label)).join(",");
  const rows = PROJECTS.map((p) => FIELDS.map(([key]) => esc(p[key])).join(","));
  return [
    "# Global CBTC Projects Database v1.0 - cbtcbook.com - free to use with attribution",
    "# Empty cells are unverified, not zero. Source: Communications-Based Train Control, Vol. 1 Ch. 10-11.",
    head,
    ...rows,
  ].join("\n") + "\n";
}
