// terms.mjs — the glossary body, grouped the way the words appear in practice
// rather than alphabetically. When an RFP starts describing the Data
// Communication System, six related terms follow in the same paragraph; reading
// by section builds the vocabulary in the order the work uses it.
//
// Definitions are deliberately short: this is a reference card, not a
// dictionary. The long-form treatment of each concept is in the manuscript.

export const GROUPS = [
  {
    title: "Core CBTC subsystems",
    terms: [
      ["CBTC", "Communications-Based Train Control. Per IEEE 1474.1: continuous automatic train control using high-resolution train location determination independent of track circuits, continuous bidirectional train-to-wayside data communications, and onboard and wayside processors implementing vital functions."],
      ["ATC", "Automatic Train Control. The umbrella for the three layers: ATC = ATP + ATO + ATS."],
      ["ATP", "Automatic Train Protection. The safety-critical layer that supervises movement against the current Movement Authority and brakes if the train would exceed it. SIL 4, mandatory at every GoA, not overridable by the driver."],
      ["ATO", "Automatic Train Operation. The driving-automation layer that commands traction and braking inside the ATP envelope: station-stopping accuracy, energy-optimized cruising, door enable."],
      ["ATS", "Automatic Train Supervision. The control-room layer: timetable execution, dispatching, regulation, route setting and operator displays. Advisory, and non-safety-critical."],
      ["ZC", "Zone Controller. The wayside computer owning one geographic zone (typically 2–5 km), tracking every train in it, issuing Movement Authorities and handing off to neighboring zones."],
      ["VOBC", "Vehicle On-Board Controller. The train-resident vital computer running ATP supervision, ATO commands, balise reading, odometry fusion and DCS communication."],
      ["OBCU", "Onboard Controller Unit. A supplier-dependent synonym for VOBC; VOBC is the preferred term in US practice."],
      ["DCS", "Data Communication System. The wireless network carrying train-to-wayside data — commonly 2.4 or 5 GHz spread-spectrum radio, increasingly LTE-R or private 5G."],
      ["CI", "Computer-based Interlocking. The processor-based successor to relay interlocking, setting and locking routes and owning switches and signals."],
      ["EI", "Electronic Interlocking. Used interchangeably with CI in most US specifications."],
      ["TIU", "Train Interface Unit. The onboard gateway between the VOBC and the train's traction, braking and door systems."],
      ["Wayside", "Everything track-side: zone controllers, interlocking, radio access points, balises and their housings."],
      ["Onboard", "Everything train-side: VOBC, antennas, odometry sensors, balise reader and the train interface."],
      ["Carborne", "A synonym for onboard, common in older US specifications and some vendor documentation."],
      ["Central", "The control-centre tier: ATS servers, operator workstations, playback and performance tooling."],
      ["OCC", "Operations Control Centre. The physical room and organization from which the railway is dispatched and supervised."],
      ["ATS workstation", "The dispatcher's console: line overview, alarms, manual intervention and route requests."],
      ["Wayside ATP", "The portion of the protection function computed track-side, principally in the zone controller, as distinct from onboard ATP."],
      ["Trackside object controller", "A distributed unit that drives points, signals or other field elements on behalf of the interlocking, reducing cable runs."],
    ],
  },
  {
    title: "Separation, capacity and movement",
    terms: [
      ["MA", "Movement Authority. The wayside's signed permission to a single train to proceed to a defined point at a defined speed. Refreshed every 200–500 ms in modern deployments."],
      ["EoA", "End of Authority. The point at which a Movement Authority terminates; ATP enforces a braking curve that stops the train short of it under worst-case assumptions."],
      ["LoA", "Limit of Authority. Used interchangeably with EoA by several suppliers."],
      ["SvL", "Supervised Location. The protected point beyond the EoA that the safe braking calculation actually targets, providing the overlap margin."],
      ["Moving block", "CBTC's defining concept: a continuously recomputed separation buffer sized to speed, braking performance and the position of the train ahead."],
      ["Fixed block", "Traditional separation: the track is divided into sections, each occupied by at most one train. Capacity is bounded by block length."],
      ["Virtual block", "A software-defined block used where full moving block is not implemented; separation is finer-grained than physical track circuits but still quantized."],
      ["Block (CBTC context)", "A short virtual segment, typically 100–200 m, used for position reference and balise placement — not the unit of separation."],
      ["Headway", "The time between successive trains at a fixed point. The primary CBTC capacity metric."],
      ["TPHPD", "Trains Per Hour Per Direction. The throughput equivalent of headway, and the number most business cases are actually judged on."],
      ["Design headway", "The headway the system is engineered to sustain, as distinct from the timetabled headway actually operated."],
      ["Dwell", "The time a train spends stopped at a platform. Above roughly 100-second headways, dwell variability rather than signaling usually sets the ceiling."],
      ["Braking curve", "The deceleration profile ATP enforces from current speed to the EoA, accounting for grade, brake fall-off, traction cutoff and worst-case reaction time."],
      ["Safe braking distance", "The worst-case distance from current speed to a full stop. Drives the size of the moving-block buffer."],
      ["Guaranteed emergency brake rate", "The deceleration the train is contractually assumed to achieve under worst-case conditions; the safety case is built on it, not on typical performance."],
      ["Service brake", "Normal deceleration commanded by ATO or the driver, inside the ATP envelope."],
      ["Emergency brake", "Maximum deceleration commanded by ATP when the envelope would otherwise be exceeded. Not modulated."],
      ["Overspeed", "Any state in which actual speed exceeds the permitted curve; the trigger for ATP intervention."],
      ["Civil speed limit", "The permanent speed restriction imposed by track geometry and structures, enforced by ATP independent of any temporary restriction."],
      ["TSR", "Temporary Speed Restriction. A time-limited limit applied for works or defects, distributed through ATS and enforced by ATP."],
      ["Coasting", "Running without traction to save energy; a standard ATO optimization where the timetable allows the run time."],
      ["Regulation", "The ATS function that adjusts dwell and run time to hold the timetable or an even headway after a perturbation."],
      ["Turnback", "Reversing a train at a terminal or mid-line crossover. Often the true capacity constraint on a converted line."],
      ["Junction margin", "The spacing reserved at a converging junction so conflicting moves can be sequenced without braking the following train."],
    ],
  },
  {
    title: "Position and odometry",
    terms: [
      ["Odometry", "The onboard estimate of distance travelled, produced by fusing several sensors, each with different failure characteristics."],
      ["Tachometer", "A wheel-mounted rotation sensor. Accurate but corrupted by wheel slip, slide and wheel-diameter wear."],
      ["Doppler radar", "A ground-facing speed sensor that is immune to wheel slip, used to bound tachometer error."],
      ["Accelerometer", "An inertial sensor providing a third, independent estimate for the odometry fusion."],
      ["Balise", "A passive trackside transponder providing an absolute position reference when the train passes over it, bounding accumulated odometry drift."],
      ["Transponder", "The generic term for a balise or tag; usage varies by supplier."],
      ["Balise reader", "The onboard antenna and processor that energizes and reads balises."],
      ["Position uncertainty", "The interval within which the train's true position is guaranteed to lie. ATP protects against the worst end of it, never the estimate."],
      ["Front-of-train / rear-of-train", "The two ends of the position uncertainty envelope. Separation is computed from the worst case of each: rear of the leader, front of the follower."],
      ["Drift", "Accumulated odometry error between balise reads. Its growth rate sets the maximum permissible balise spacing."],
      ["Wheel slip / slide", "Loss of adhesion in traction or braking, the dominant source of tachometer error and the reason for sensor fusion."],
      ["Re-railing / re-localization", "Re-establishing a train's confirmed position after it has been lost, typically requiring a balise pass at restricted speed."],
      ["Localized / non-localized", "Whether a train currently has a valid, bounded position. A non-localized train is protected far more conservatively."],
      ["Train integrity", "Confirmation that the train is complete and no vehicles have detached. Assumed structurally on most metro fleets; explicitly monitored on others."],
      ["Track database", "The onboard and wayside model of the alignment: geometry, gradients, speed limits, balise locations and topology."],
      ["Guideway", "The running way, used in preference to 'track' for automated and rubber-tyred systems."],
    ],
  },
  {
    title: "Communications",
    terms: [
      ["Radio access point", "The trackside radio unit, typically every 250–500 m with overlapping coverage, forming the DCS."],
      ["Handover", "The transfer of a train's radio association from one access point to the next, or of protection responsibility from one zone controller to the next."],
      ["Heartbeat", "A periodic health message between train and wayside, or between redundant processors. Its absence for a defined interval triggers a defined fallback."],
      ["Latency budget", "The end-to-end delay allowance from measurement to enforcement, apportioned across the chain and verified in test."],
      ["Jitter", "Variation in message delay. Sustained jitter degrades the achievable headway even when average latency is within budget."],
      ["Packet loss", "Messages lost in transit. The protection design assumes a rate and degrades safely beyond it."],
      ["ISM band", "The unlicensed 2.4 and 5 GHz spectrum most legacy CBTC radio uses — cheap, and shared with everything else."],
      ["LTE-R", "Cellular-grade radio adapted for railway use; a migration path away from unlicensed spectrum."],
      ["Private 5G", "A dedicated cellular network on licensed or shared spectrum, increasingly proposed as the DCS bearer."],
      ["FRMCS", "Future Railway Mobile Communication System. The European successor to GSM-R; relevant to US agencies mainly through vendor roadmaps."],
      ["Inductive loop", "The pre-radio train-to-wayside bearer: a cable laid along the track. Still in service on some early systems."],
      ["Redundant radio", "Two or more independent radio paths per train, so a single antenna or access-point failure does not cost the position report."],
      ["Message authentication", "Cryptographic verification that a position report or Movement Authority came from the claimed source and was not altered."],
      ["Replay protection", "Ensuring an intercepted valid message cannot be re-injected later — a basic requirement of any vital protocol."],
      ["RSSI", "Received Signal Strength Indication. The field measurement used to verify radio coverage along the alignment during SIT."],
      ["Coverage survey", "The systematic measurement of radio performance along the whole line, which no lab simulator can substitute for."],
    ],
  },
  {
    title: "Automation grades and operating modes",
    terms: [
      ["GoA", "Grades of Automation. The IEC 62290-1 framework allocating responsibility across five levels, GoA 0 to GoA 4."],
      ["GoA 0", "On-sight operation. The driver drives by line of sight, with no automatic protection."],
      ["GoA 1", "Non-automated train operation. The driver drives; ATP supervises and intervenes."],
      ["GoA 2", "Semi-automated train operation. ATO drives inside the ATP envelope; the driver closes doors and handles disruption. The US norm."],
      ["GoA 3", "Driverless train operation. No driver; an attendant on board manages disruption and evacuation."],
      ["GoA 4", "Unattended train operation. No operating staff required on board; disruption and evacuation fall to the control centre and automation."],
      ["UTO", "Unattended Train Operation — the operational name for GoA 4."],
      ["DTO", "Driverless Train Operation — GoA 3."],
      ["STO", "Semi-automated Train Operation — GoA 2."],
      ["NTO", "Non-automated Train Operation — GoA 1."],
      ["Normal mode", "Full CBTC operation with a valid Movement Authority and a localized train."],
      ["Restricted manual", "Driving under a low absolute speed limit with ATP protection reduced or absent; the usual fallback when position is lost."],
      ["Degraded mode", "Any defined operating state below full CBTC performance, entered deliberately and with a defined exit."],
      ["Failure mode", "An unplanned state the design must render safe, as distinct from a degraded mode the design provides for."],
      ["Fallback", "The defined transition from one operating mode to a lower one when a condition is lost."],
      ["Mixed mode", "CBTC-equipped and non-equipped trains sharing track. Capacity is governed by the least-capable train type."],
      ["Shadow mode", "CBTC monitoring live traffic and logging decisions without controlling trains. Also called ghost mode."],
      ["Degraded-mode ladder", "The ordered sequence of fallbacks from normal operation down to restricted manual, each with its own entry and exit criteria."],
      ["Wake-up / sleep", "Automated start-up and shutdown of an unattended train, including the self-test sequence that must pass before it can move."],
      ["Auto-reverse", "Automated turnback at a terminal without staff intervention — a GoA 4 requirement and a common capacity constraint."],
    ],
  },
];

GROUPS.push(
  {
    title: "Safety and assurance",
    terms: [
      ["SIL", "Safety Integrity Level. A 1–4 scale of the rigour demanded of a safety function. ATP is SIL 4; ATO is SIL 0–2 depending on GoA; ATS is SIL 0."],
      ["SIL 4", "The highest level, corresponding to a tolerable hazard rate between 10⁻⁹ and 10⁻⁸ dangerous failures per hour. A design posture and an evidence burden, not a certificate you buy."],
      ["THR", "Tolerable Hazard Rate. The quantified frequency at which a specified hazard may occur; the numeric target a SIL allocation encodes."],
      ["Vital", "Any function whose failure can cause a hazard, and which must therefore be implemented to fail safe."],
      ["Non-vital", "A function whose failure degrades performance but cannot by itself cause a hazard."],
      ["Fail-safe", "A design property: on failure, the system reaches a state that is safe — usually stopped — rather than an unpredictable one."],
      ["Safety case", "The structured argument, with evidence, that a system is acceptably safe for a defined use in a defined context."],
      ["Hazard log", "The living register of identified hazards with their analysis, mitigation and closure status. Auditable throughout the project."],
      ["HAZOP", "Hazard and Operability study. A structured, guideword-driven group analysis of deviations from design intent."],
      ["FMEA", "Failure Modes and Effects Analysis. Bottom-up: for each component failure, what happens?"],
      ["FTA", "Fault Tree Analysis. Top-down: for a defined hazard, which combinations of failures produce it? (Not to be confused with the Federal Transit Administration.)"],
      ["ISA", "Independent Safety Assessor. A party independent of the delivery team that assesses the safety case and its evidence."],
      ["V&V", "Verification and Validation. Verification asks whether the system was built to the requirements; validation asks whether the requirements were the right ones."],
      ["RAMS", "Reliability, Availability, Maintainability and Safety. The contractual quality attributes of a rail system, per EN 50126."],
      ["MTBF", "Mean Time Between Failures. Usually specified per subsystem and measured over a defined revenue period."],
      ["MTTR", "Mean Time To Repair. Combined with MTBF, it sets achievable availability."],
      ["Availability", "The proportion of scheduled service time the system is capable of delivering. Contractually defined, and the definition matters more than the number."],
      ["Common cause failure", "A single cause defeating supposedly redundant channels — the failure mode redundancy alone does not address."],
      ["Diversity", "Deliberately different implementations of the same function so a design fault does not defeat both channels."],
      ["2oo2 / 2oo3", "Two-out-of-two and two-out-of-three voting architectures for vital processors; 2oo2 fails safe on disagreement, 2oo3 continues on a majority."],
      ["Safe state", "The condition the system enters when it can no longer assure safety — typically brakes applied and movement authority withdrawn."],
      ["Systematic failure", "A failure arising from a design or process fault rather than random hardware failure. Not reducible by redundancy; addressed by process rigour."],
    ],
  },
  {
    title: "Standards and regulatory",
    terms: [
      ["IEEE 1474.1", "Performance and functional requirements for CBTC. The US procurement floor; specifying 'CBTC' without citing it leaves the definition to the vendor."],
      ["IEEE 1474.2", "User interface requirements for CBTC."],
      ["IEEE 1474.3", "Recommended practice for CBTC system design and functional allocation."],
      ["IEEE 1474.4", "Recommended practice for functional testing of CBTC."],
      ["IEC 62290-1", "System requirements and the GoA definitions, including the responsibility allocation matrix."],
      ["IEC 62290-2", "Functional requirements for ATP, ATO and ATS across the automation grades."],
      ["IEC 62290-3", "System requirements specification guidance; later parts extend to cybersecurity and test specification."],
      ["EN 50126", "The RAMS lifecycle standard for railway applications."],
      ["EN 50128", "Software for railway control and protection systems."],
      ["EN 50129", "Safety-related electronic systems for signalling, and the structure of the safety case."],
      ["EN 50159", "Safety-related communication in transmission systems — the basis for vital messaging over an open network."],
      ["IEC 62443", "The industrial cybersecurity series increasingly cited for rail signalling networks."],
      ["FTA", "Federal Transit Administration. The federal funder and oversight body for US transit capital projects."],
      ["SSO", "State Safety Oversight. The state agency with safety jurisdiction over a rail transit system, under FTA rules."],
      ["PMOC", "Project Management Oversight Contractor. FTA's agent reviewing a funded project's readiness, including the System Integration Review gate."],
      ["CIG", "Capital Investment Grant. The FTA funding programme whose requirements shape scope, schedule and reporting."],
      ["Buy America", "The domestic-content requirement attached to federal funding; all tier-1 CBTC suppliers maintain US facilities to satisfy it."],
      ["APTA", "American Public Transportation Association. Publishes industry standards and recommended practice used across US procurement."],
    ],
  },
  {
    title: "Procurement and contract",
    terms: [
      ["RFP", "Request for Proposal. The document whose specification quality determines most of what follows."],
      ["ICD", "Interface Control Document. The per-interface specification of message formats, timing, failure modes and acceptance criteria. Its absence is the most reliable predictor of schedule slip."],
      ["Performance-based specification", "A specification stating required outcomes — headway, availability, latency — rather than prescribing an implementation."],
      ["Prescriptive specification", "A specification dictating the design. Reduces vendor freedom and transfers design risk to the owner."],
      ["Bundled procurement", "Signalling and rolling stock (or civils) procured under one contract, giving single-prime accountability for integration."],
      ["Unbundled procurement", "Separate contracts per scope. Cheaper on paper; the integration risk returns to the owner."],
      ["Single-prime", "One contractor accountable for the integrated outcome, as on the Honolulu Skyline vehicle-and-signalling contract."],
      ["Owner's engineer", "The owner's technical representative with the standing to reject a vendor interpretation. Its absence is felt at design review."],
      ["PMC", "Program Management Consultant. Represents the owner in schedule, cost and technical oversight."],
      ["Liquidated damages", "Pre-agreed sums payable for defined failures to perform, structured before award rather than negotiated after."],
      ["Performance guarantee", "A contractual commitment to a measurable outcome, typically headway and availability, with a defined demonstration method."],
      ["Vendor lock-in", "The condition where the platform choice makes future work non-competitive. In CBTC it is structural, not accidental, which is why data rights belong in the RFP."],
      ["Data rights", "Ownership of and access to interface definitions, configuration data and logs — the practical determinant of whether a second supplier can ever bid."],
      ["Second source", "A viable alternative supplier for a component or scope. Common in fixed-block signalling, rare in CBTC."],
      ["Change order", "A contractual variation. The instrument through which under-specified interfaces become expensive."],
      ["Scope of work", "The definition of what is being bought. Where an ICD is absent, the SOW is where that gap will surface."],
      ["Basis of design", "The stated assumptions the design is built on — fleet, timetable, alignment — which every later dispute returns to."],
      ["Contingency", "Budgeted allowance for identified risk. On brownfield CBTC it is consumed disproportionately by interface and access issues."],
    ],
  },
  {
    title: "Project lifecycle and testing",
    terms: [
      ["V-model", "The development lifecycle pairing each specification level with the test level that verifies it."],
      ["FAT", "Factory Acceptance Test. Vendor lab, 6–12 weeks, typically 60–90 percent functional coverage of the final system."],
      ["SIT", "Site Integration Testing. On site with real hardware, radio and geometry; typically 12–20 weekends on a mid-size line."],
      ["Dynamic testing", "The first train movements under CBTC control, progressing through defined scenarios; typically 4–8 weeks."],
      ["Shadow running", "CBTC logging live traffic without controlling it. Best practice on US brownfield is 6–12 months."],
      ["Parallel operations", "CBTC and legacy trains sharing track during transition; typically 2–8 weeks."],
      ["RSD", "Revenue Service Demonstration. Full CBTC control with passengers at limited service levels, 2–4 weeks before full cutover."],
      ["HIL", "Hardware-in-the-Loop. Production code run against a simulated railway, allowing repeatable and otherwise unsafe scenarios."],
      ["Simulator", "A full-system model of track, trains and wayside used to validate thousands of scenarios before on-track testing. Reduces on-track time; does not replace it."],
      ["Cutover", "The transition from legacy signalling to CBTC. The highest-risk event in the lifecycle — it does not create problems, it reveals them."],
      ["MOP", "Method of Procedure. The minute-by-minute choreography of the cutover window. A good one runs 60–100 pages; a 15-page MOP manufactures false confidence."],
      ["Cutover rehearsal", "A full dress rehearsal 4–6 weeks before the event with the same staff, equipment and timeline."],
      ["Rollback criteria", "The pre-defined, objective conditions under which the cutover is abandoned and the legacy system restored. Decided before the window, not inside it."],
      ["War room", "The command centre during cutover, with named roles and pre-assigned decision authority — including who may stop it."],
      ["Big bang", "Full-line conversion in one extended shutdown, typically 3–7 days. Defensible on greenfield; rarely on an operating urban line."],
      ["Segment-phased", "Conversion by geographic section over weeks or months. The most common US brownfield strategy."],
      ["Fleet-phased", "Retrofit by depot or batch over 18–36 months, with a correspondingly long mixed-mode period."],
      ["Function-phased", "ATP first, ATO later, each with its own cutover and ramp."],
      ["Burn-in", "The first 30–90 days of revenue service, run as a managed ramp with reduced schedule and vendor engineering on site."],
      ["Punch list", "The register of outstanding defects at handover, each with an owner and a closure date."],
    ],
  },
  {
    title: "Interfaces and the wider estate",
    terms: [
      ["System boundary", "Per IEC 62290, the CBTC system comprises ATP, ATO and ATS — and nothing else. Everything beyond it is external infrastructure behind an interface."],
      ["PSD", "Platform Screen Door. Full- or half-height barriers at the platform edge, mandatory in practice for GoA 4. Operates on independent position sensing, not on CBTC's word."],
      ["PED", "Platform Edge Door. A half-height variant of PSD."],
      ["SCADA", "Supervisory Control and Data Acquisition. Traction power, ventilation and station plant; interfaces with CBTC for power status and regenerative braking coordination."],
      ["PIS", "Passenger Information System. Consumes ATS predictions to drive platform and in-car displays."],
      ["AFC", "Automatic Fare Collection. Outside the boundary, but shares station infrastructure and sometimes the same network."],
      ["BAS", "Building Automation System. Station environmental and plant control."],
      ["Depot management", "Stabling, washing and maintenance movements. Often the last scope to be automated and a frequent source of late change."],
      ["OPC-UA", "A vendor-neutral industrial protocol commonly used for the SCADA interface."],
      ["Hardwired interface", "A relay-level connection. Absolutely fail-safe, inflexible, and still the right answer for some interlocking interfaces."],
      ["Gateway", "A translating device between a legacy protocol and the CBTC. Its ownership — vendor or owner — must be settled in the contract."],
      ["Legacy overlay", "CBTC installed over retained conventional signalling, which remains available as a fallback."],
      ["Greenfield", "A new line with no inherited signalling, operating rules or fleet constraints."],
      ["Brownfield", "Conversion of an operating railway. The brownfield tax — access, interfaces, mixed running — is what makes international unit costs travel badly."],
      ["Track circuit", "The legacy train-detection method: wheels short a rail-borne circuit. Retained in CBTC territory only where interlocking or fallback requires it."],
      ["Axle counter", "An alternative detection method counting axles into and out of a section; less susceptible to rust and shunt problems than a track circuit."],
    ],
  },
  {
    title: "Suppliers, platforms and adjacent systems",
    terms: [
      ["Trainguard MT", "Siemens Mobility's CBTC platform. NYCT Line 7 and the L Line; Paris Line 1."],
      ["SelTrac", "The CBTC platform originating with Alcatel, then Thales, and part of Hitachi Rail since May 2024. Vancouver SkyTrain, London Jubilee, BART TCMP."],
      ["Urbalis", "Alstom's CBTC platform, incorporating the former Bombardier CITYFLO line after the 2021 acquisition."],
      ["CITYFLO", "Bombardier's CBTC family, now within Alstom. CITYFLO 650 is the moving-block variant."],
      ["Ansaldo STS", "The Italian signalling house behind Copenhagen's driverless metro, now part of Hitachi Rail."],
      ["CRSC / TCT", "Chinese suppliers dominating domestic metropolitan CBTC, with an estimated 15–20 percent of the global market and effectively no North American presence."],
      ["PTC", "Positive Train Control. The US mainline overspeed and signal-enforcement mandate. Not CBTC: fixed-block, far coarser, different regulator."],
      ["I-ETMS", "Wabtec's interoperable PTC platform, deployed across roughly 15,000 km of US freight railroad."],
      ["ERTMS", "European Rail Traffic Management System — the mainline framework of which ETCS is the train-control component."],
      ["ETCS", "European Train Control System. Level 2 is radio-based with fixed blocks; Level 3 approaches moving block. Mainline, not metro."],
      ["Hybrid Level 3", "An ETCS variant subdividing fixed blocks using train-reported position — conceptually adjacent to CBTC, on mainline infrastructure."],
      ["Virtual coupling", "A research-stage concept in which trains run at absolute-braking-distance separation by exchanging state train-to-train. Not deployed in revenue service."],
    ],
  },
);
