#!/usr/bin/env python3
"""
build_queue.py — Generate publish-queue.yml with a balanced cross-cluster
publication schedule.

Defaults match the negotiated cadence:
  - 2-3 articles per weekday (Mon/Wed/Fri = 3, Tue/Thu = 2 = 13/week)
  - cross-cluster mixing (don't publish 3 articles from same cluster on
    one day — looks like a script to Google's helpful-content classifier)
  - skip weekends initially (publish-queue.yml is editable; user can add
    Saturday slots later if they want)
  - start the next Monday after today

Output format:
    "2026-05-11":
      - what-is-cbtc-2026-guide
      - cbtc-rfp-vendor-lockin
      - nyc-mta-l-line-cbtc-25-years
    "2026-05-12":
      - moving-block-explained
      - cbtc-procurement-cost-drivers
    ...

Usage:
    python3 build_queue.py                    # default: starts next Monday, 7-8 weeks
    python3 build_queue.py --start 2026-05-11
    python3 build_queue.py --dry              # print without writing
"""
from __future__ import annotations
import argparse
import datetime as dt
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DRAFTS = ROOT / "blog-drafts"
ARTICLE_LIST = ROOT / "blog-drafts" / "_FLEET_SUMMARY.md"
OUT = ROOT / "publish-queue.yml"

# Articles per weekday — index 0 = Monday
WEEKDAY_COUNTS = [3, 2, 3, 2, 3, 0, 0]   # Mon, Tue, Wed, Thu, Fri, Sat, Sun


def parse_clusters() -> list[tuple[str, list[str]]]:
    """Parse cbtcbook-blog-100-articles.md to recover (cluster_name, slugs)."""
    if not ARTICLE_LIST.exists():
        # Fallback: read frontmatter from each draft
        return [("all", sorted(p.stem for p in DRAFTS.glob("*.md")
                               if not p.stem.startswith("_")))]
    text = ARTICLE_LIST.read_text(encoding="utf-8")
    clusters: list[tuple[str, list[str]]] = []
    current_name = None
    current_slugs: list[str] = []
    for line in text.splitlines():
        # FLEET_SUMMARY.md uses "### Cluster ① Definitional ..."
        h = re.match(r"^###\s+Cluster\s+\S+\s+(.+?)\s*\(", line)
        if h:
            if current_name and current_slugs:
                clusters.append((current_name, current_slugs))
            current_name = h.group(1).strip().rstrip("/").lower()
            current_slugs = []
            continue
        m = re.match(r"^\s*\d+\.\s+`([a-z0-9-]+)\.md`", line)
        if m:
            current_slugs.append(m.group(1))
    if current_name and current_slugs:
        clusters.append((current_name, current_slugs))
    return clusters


def existing_slugs() -> set[str]:
    return {p.stem for p in DRAFTS.glob("*.md") if not p.stem.startswith("_")}


def round_robin(clusters: list[tuple[str, list[str]]]) -> list[str]:
    """Interleave slugs across clusters so adjacent items are from
    different clusters whenever possible. Preserves intra-cluster order."""
    queues = [list(slugs) for _, slugs in clusters]
    out: list[str] = []
    while any(queues):
        for q in queues:
            if q:
                out.append(q.pop(0))
    return out


def schedule(slugs: list[str], start: dt.date) -> dict[str, list[str]]:
    queue = list(slugs)
    sched: dict[str, list[str]] = {}
    day = start
    while queue:
        n = WEEKDAY_COUNTS[day.weekday()]
        if n > 0:
            sched[day.isoformat()] = [queue.pop(0) for _ in range(min(n, len(queue)))]
        day += dt.timedelta(days=1)
        if day - start > dt.timedelta(days=200):
            raise SystemExit("schedule overflow — adjust WEEKDAY_COUNTS")
    return sched


def to_yaml(sched: dict[str, list[str]]) -> str:
    lines: list[str] = [
        "# publish-queue.yml — daily publication schedule for cbtcbook.com/blog/",
        "# Generated by blog-tools/build_queue.py",
        "# Edit freely. Each date maps to a list of slugs from /blog-drafts/.",
        "# daily-publish.sh reads this file and copies today's slugs into the",
        "# Astro content collection, then builds and deploys.",
        "",
    ]
    for date, slugs in sorted(sched.items()):
        lines.append(f'"{date}":')
        for s in slugs:
            lines.append(f"  - {s}")
    return "\n".join(lines) + "\n"


def next_monday(today: dt.date) -> dt.date:
    days_until = (0 - today.weekday()) % 7
    return today + dt.timedelta(days=days_until or 7)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--start", help="ISO date (YYYY-MM-DD); default = next Monday")
    ap.add_argument("--dry", action="store_true", help="print without writing")
    args = ap.parse_args()

    today = dt.date.today()
    start = (
        dt.date.fromisoformat(args.start) if args.start
        else next_monday(today)
    )

    clusters = parse_clusters()
    valid = existing_slugs()

    # Filter to slugs that actually exist on disk; warn on any missing
    filtered: list[tuple[str, list[str]]] = []
    missing: list[str] = []
    for name, slugs in clusters:
        keep, lose = [], []
        for s in slugs:
            (keep if s in valid else lose).append(s)
        if keep:
            filtered.append((name, keep))
        missing.extend(lose)
    if missing:
        print(f"⚠️  {len(missing)} planned slugs not found on disk: "
              f"{missing[:3]}{'…' if len(missing) > 3 else ''}")

    interleaved = round_robin(filtered)
    sched = schedule(interleaved, start)
    yaml_text = to_yaml(sched)

    days = len(sched)
    total = sum(len(v) for v in sched.values())
    end_date = max(sched.keys())
    print(f"Generated schedule: {total} articles across {days} days")
    print(f"  Start: {start.isoformat()}  →  End: {end_date}")
    print(f"  Cadence: {WEEKDAY_COUNTS[:5]} on Mon-Fri")

    if args.dry:
        print("\n--- queue (first 12 days) ---")
        for d in list(sorted(sched.keys()))[:12]:
            print(f'"{d}":')
            for s in sched[d]:
                print(f"  - {s}")
        return 0

    OUT.write_text(yaml_text, encoding="utf-8")
    print(f"\nWrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
