#!/usr/bin/env python3
"""
map-figures.py — Replace [FIGURE: ...] placeholders that reference EXISTING book
figures with proper markdown <img> syntax. List remaining "needs new figure"
placeholders to images-todo.md for downstream image generation.

Run:  python3 map-figures.py
Output: rewrites .md files in-place and generates images-todo.md.
"""

import re, os, sys
from pathlib import Path
from collections import defaultdict

# Auto-detect base path: works both on the user's Mac and the sandbox
_CANDIDATES = [
    Path("/Users/chunjun/CBTC_book_site"),
    Path("/sessions/determined-awesome-davinci/mnt/CBTC_book_site"),
]
BASE = next((p for p in _CANDIDATES if p.exists()), None) or _CANDIDATES[0]
DRAFTS      = BASE / "blog-drafts"
FIGURES_DIR = BASE / "site" / "figures"
IMAGES_TODO = BASE / "blog-drafts" / "_IMAGES_TODO.md"
DRY_RUN = "--apply" not in sys.argv  # default: dry-run; pass --apply to write

# Pattern: [FIGURE: <description>. Source: <source>. Caption: "<caption>"]
# Multi-line, may span 3+ lines.
FIG_RE = re.compile(
    r'\[FIGURE:\s*(?P<desc>.*?)\.\s*'
    r'Source:\s*(?P<src>.*?)\.\s*'
    r'Caption:\s*"(?P<cap>.*?)"\s*\]',
    re.DOTALL,
)

EXISTING_FIG_RE = re.compile(r'(fig_\d+_\d+_[a-z_]+\.png)', re.IGNORECASE)

def main():
    if not DRAFTS.exists():
        print(f"ERROR: {DRAFTS} not found"); sys.exit(1)

    # Build set of existing figure filenames
    existing_figs = {f.name for f in FIGURES_DIR.glob("fig_*.png")}
    print(f"Found {len(existing_figs)} existing figures in {FIGURES_DIR}")

    todo_by_article = defaultdict(list)
    replaced_count = 0
    todo_count = 0

    for md_file in sorted(DRAFTS.glob("*.md")):
        if md_file.name.startswith("_"):
            continue  # skip reports

        text = md_file.read_text()
        new_text = text
        offset = 0

        for match in FIG_RE.finditer(text):
            desc = match.group("desc").strip()
            src = match.group("src").strip()
            cap = match.group("cap").strip()

            # Detect if Source references an existing book figure
            fig_match = EXISTING_FIG_RE.search(src)
            if fig_match and fig_match.group(1) in existing_figs:
                # Replace with markdown image
                fig_name = fig_match.group(1)
                replacement = (
                    f"![{cap}](/figures/{fig_name})\n"
                    f"*<small>{cap}</small>*"
                )
                start, end = match.start() + offset, match.end() + offset
                new_text = new_text[:start] + replacement + new_text[end:]
                offset += len(replacement) - (end - start)
                replaced_count += 1
            else:
                # Needs new figure — log to images-todo
                todo_by_article[md_file.name].append({
                    "desc": desc[:120],
                    "src": src[:80],
                    "cap": cap[:120],
                })
                todo_count += 1

        if new_text != text:
            if not DRY_RUN:
                md_file.write_text(new_text)
            print(f"  [{'DRY' if DRY_RUN else 'OK '}] {md_file.name}: replaced {len([m for m in FIG_RE.finditer(text) if EXISTING_FIG_RE.search(m.group('src')) and EXISTING_FIG_RE.search(m.group('src')).group(1) in existing_figs])} figure(s)")

    # Write images-todo.md
    todo_md = ["# Images To Generate\n",
               f"Auto-generated by map-figures.py from FIGURE placeholders that do NOT match an existing book figure.\n",
               f"\n**{todo_count} new images** needed across **{len(todo_by_article)} articles**.\n\n",
               "Each entry below should be either:\n",
               "1. Generated via OpenAI image API / DALL-E (technical concept illustrations, hero images)\n",
               "2. Drawn manually in Excalidraw / draw.io (architecture / flow diagrams)\n",
               "3. Replaced with an HTML `<table>` in-place if the description is essentially tabular data\n\n",
               "---\n\n"]

    for article, figs in sorted(todo_by_article.items()):
        todo_md.append(f"## {article}\n\n")
        for i, f in enumerate(figs, 1):
            todo_md.append(f"**Figure {i}**\n")
            todo_md.append(f"- **Description**: {f['desc']}\n")
            todo_md.append(f"- **Source hint**: {f['src']}\n")
            todo_md.append(f"- **Caption**: {f['cap']}\n\n")
        todo_md.append("\n")

    if not DRY_RUN:
        IMAGES_TODO.write_text("".join(todo_md))

    print()
    print("=" * 60)
    print(f"Mode:                   {'DRY-RUN (use --apply to write)' if DRY_RUN else 'APPLIED'}")
    print(f"Existing figures reused:    {replaced_count}")
    print(f"New figures needed:         {todo_count}")
    print(f"Articles with todo items:   {len(todo_by_article)}")
    if not DRY_RUN:
        print(f"\nimages-todo.md written to:  {IMAGES_TODO}")


if __name__ == "__main__":
    main()
